---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: matrix
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    redis-password: AgA64n6qiHUMlaHNV8yYNNTAo+9m/YHwxCS313kHP6j7iEqawF2IqEvYr18HxQCnL7qSPGkojLX5J2wfiSOtYZ/kmfdwtd3KwsFo0wT8DQMy0H8xcdt0TTp6zJ8hLWO+jbCRqth511xzH1I0NVP3OzoNtm7z7GiuMM9+JcXzvJvghkdyv7YwgxHZUI0ODRwgqiAATagfaVwm7iIwhIOnF3Ydru7JdZrXjFe03zQMXiqKtxJJAgN/6KPOebC0XNEQDtUvX7jdB1ADKi0Nb22B1ppru841JT1f2gKZm/NcAaT3iqsBMP+Ku2kGTNbCxPdX0O/P1zIrP3Yum/Hatjk21vAECtwSvbEZt/BLNXzZltFQRMD6DXhFfYvIZZfA9Z3qI20B8QvWzOzYLapvybXQozOtfDzZem9+kyLlOzCcixODgo3nSCqDLW73BCYXhjsHNBh3rC589S5EPNrbxoQor+4MiV2pVDeNzu4QqiB/UnVKs1Q9pOHoK52+1tL7gltNF1Xkdk9r7EWXvwX2/HucAhTwY0xk6b4rpMqyj2FjZvyq5tucOMkukWokjVjDJeIviXanpKEzc0K0RsEt7YCOU0r5+a+IJMqLGaUpxo5LO0puR8Q0CMjXmH/D6UaZC+O86+X7q0zBab/FdNMG9mavC8/MsEco8dKybJufGVn3MzQwCf772EjXvaeAFN5nwgYu1m6liuP3rBEcXQ2b/sGNfgfOa79uhxLuOs6+dkNbL8LQ6mdCJqRVrhKccVIk6U6I
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: matrix
    type: Opaque
