controller:
  config:
    use-proxy-protocol: "true"
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  extraArgs:
    enable-ssl-passthrough: "true"
  kind: DaemonSet
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
  extraContainers:
    - name: grafana-alloy
      image: grafana/alloy:latest
      args:
        - run
        - /etc/alloy/audit-logs.alloy
      volumeMounts:
        - name: audit-logs
          mountPath: /var/log/audit
        - name: alloy-config
          mountPath: /etc/alloy
  extraVolumeMounts:
    - name: audit-logs
      mountPath: /var/log/audit
  extraVolumes:
    - name: audit-logs
      emptyDir:
        sizeLimit: 1Gi
    - name: alloy-config
      configMap:
        name: alloy-audit-config
