controller:
  extraEnvs:
    - name: MAXMIND_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          key: MAXMIND_LICENSE_KEY
          name: maxmind
  maxmindLicenseKey: "$(MAXMIND_LICENSE_KEY)"
  config:
    use-proxy-protocol: "true"
    use-geoip2: "true"
    geoip2-autoreload-in-minutes: 1440
    strict-validate-path-type: "false"
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", "requestID": "$req_id", "proxyUpstreamName":
    "$proxy_upstream_name", "proxyAlternativeUpstreamName": "$proxy_alternative_upstream_name","upstreamStatus":
    "$upstream_status", "upstreamAddr": "$upstream_addr","httpRequest":{"requestMethod":
    "$request_method", "requestUrl": "$host$request_uri", "status": $status,"requestSize":
    "$request_length", "responseSize": "$upstream_response_length", "userAgent": "$http_user_agent",
    "remoteIp": "$remote_addr", "countryCode": "$geoip2_city_country_code", "regionName": "$geoip2_region_name",
    "referer": "$http_referer", "latency": "$upstream_response_time s", "protocol": "$server_protocol"}}'
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  extraArgs:
    enable-ssl-passthrough: "true"
  kind: DaemonSet
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
