controller:
  extraEnvs:
    - name: MAXMIND_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          key: MAXMIND_LICENSE_KEY
          name: maxmind
  maxmindLicenseKey: "$(MAXMIND_LICENSE_KEY)"
  config:
    use-proxy-protocol: "true"
    use-geoip2: "true"
    geoip2-autoreload-in-minutes: 1440
    strict-validate-path-type: "false"
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", "requestID": "$req_id", "proxyUpstreamName":
    "$proxy_upstream_name", "proxyAlternativeUpstreamName": "$proxy_alternative_upstream_name","upstreamStatus":
    "$upstream_status", "upstreamAddr": "$upstream_addr","httpRequest":{"requestMethod":
    "$request_method", "requestUrl": "$host$request_uri", "status": $status,"requestSize":
    "$request_length", "responseSize": "$upstream_response_length", "userAgent": "$http_user_agent",
    "remoteIp": "$remote_addr", "countryCode": "$geoip2_city_country_code", "regionName": "$geoip2_region_name",
    "referer": "$http_referer", "latency": "$upstream_response_time s", "protocol": "$server_protocol"}}'
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  extraArgs:
    enable-ssl-passthrough: "true"
  kind: DaemonSet
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
  extraVolumes:
    - name: modsecurity-configs
      configMap:
        name: modsecurity-configs
    - name: custom-ip-blacklist
      configMap:
        name: custom-ip-blacklist
    - name: malicious-ip
      emptyDir: {}
  extraVolumeMounts:
    - name: modsecurity-configs
      mountPath: /etc/nginx/modsecurity-configs
    - name: custom-ip-blacklist
      mountPath: /etc/custom-ip-blacklist
    - name: malicious-ip
      mountPath: /etc/malicious-ip
  extraContainers:
    - name: malicious-ip-updater
      image: curlimages/curl:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "[$(date)] Downloading malicious IP lists..."
            curl -sSLo /etc/malicious-ip/full-300k-aa.txt https://raw.githubusercontent.com/romainmarcoux/malicious-ip/main/full-300k-aa.txt
            curl -sSLo /etc/malicious-ip/full-300k-ab.txt https://raw.githubusercontent.com/romainmarcoux/malicious-ip/main/full-300k-ab.txt
            curl -sSLo /etc/malicious-ip/full-300k-ac.txt https://raw.githubusercontent.com/romainmarcoux/malicious-ip/main/full-300k-ac.txt
            curl -sSLo /etc/malicious-ip/full-300k-ad.txt https://raw.githubusercontent.com/romainmarcoux/malicious-ip/main/full-300k-ad.txt
            echo "[$(date)] Done. Sleeping for 1 hour..."
            sleep 3600
          done
      volumeMounts:
        - name: malicious-ip
          mountPath: /etc/malicious-ip

