controller:
  extraEnvs:
    - name: MAXMIND_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          key: MAXMIND_LICENSE_KEY
          name: maxmind
  maxmindLicenseKey: "$(MAXMIND_LICENSE_KEY)"
  config:
    use-proxy-protocol: "true"
    use-geoip2: "true"
    geoip2-autoreload-in-minutes: 1440
    strict-validate-path-type: "false"
    log-format-upstream: '$geoip2_data_country_code $geoip2_data_country_name $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id '
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  extraArgs:
    enable-ssl-passthrough: "true"
  kind: DaemonSet
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
