---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCNscujNN5p/4MlLQffs0IF6gyX+6hPhSEVyYoWKIiIb7EwW4GLR4vdqPjakiB1tNk44fRhCFWvAPLhM9WSgkgPsXGTGQW+EnOXTaFH8wkG9miUwwviR5lYT640jPZY/GYuMPN5vJDlxpispdGGCpvEpNn9VXCyZOdq1yOWv39Ic8vSrox6tYzRxQcdEA/ITG/PRgUCQoKAEO8de6dyNPBXmcPNW1pFiUExYVDtYaMeqDwlD6TeqscWemQ8/WX6s7Lu9be7b+aDkkxMpuW+vij/33GAjjQX6ORBqEIkm5Q1AzLCIYvZaCh6e5nay9WEL2Je4bsT+OjgocN8pRoB14On9Ply1qI5Hwbe5iw0x2dBI0I4r7IyTjeaen3N0pRRO1sMtPT1ZmzHtePAAUklQHYRx1BeM4f1bqgg+GbZ9oIhrqFQbwSsEOGiC3m+RA0LtLAV8v7Mmh1oB0E2dP4TE4w3ovKeIhtNjVAjCjdDKEpwUeZQH+3BoZa21mNwV4HPir6v3KL4w40jUs4WBmRMAqL1r2IRxotMCpU2F1EBlu++Mu2hP/i0eErGH84lE0g6/Cd487jhk8e1ZBacrbtQ22a/CX+27Bi6Oxp134Y64GBHrI1+wA9ClaawLWQFaUzHvNR7twvpd+dE4sy7b9egS9DQIkmffJULcXqW5DAkz4lFnjwPako+/Fcs0bzAQ06DPcFYqtApVlk0jhPf8lM/VihKd70Qeg==
    admin-user: AgA+Y150mpkLWNr6Da66lw/U4vzSUT6gVo/RWANs5sy4ksQuCIKKzv8wedgiv1iSBoYJ7Rvo9GUenJXx4tA3SmIF/Pfw2J2gW3JI+UHZaTwxWDhpATE48LILP400T9b9KvT63EjlwodPob/JIFtq1a/UET2ctoaIecrCoa5Fs2Nk7mLgwd55hmeKo3r09+GjGLrtMNao+O6WYFgl9GlbVIGp1slZ/IiSlX2iYM1SyDTiMB0dbUgETN03vlT8yqwbVBi6E0tbWZ3FNIU7/2Ka0iIsRqftRcmgnVdnWMxkJM1jeuF47j+70Njvx3EVaRkmY5CG0aSyvxq0SogojhA90nHtKNR6Rwc1YORPiZ22NBSwqGNC4VKB79mRQrsTM3Obiawj6/KQOqnrGlDLdFyvqIqKGYi/CfOgKGS8PPsXE5U04w+VJMVi7tLpvsBYjmcDk3/emn+cg6en7L3DX5yHz3GkQ62liDhgDu9Hq+37XssARblKFXFA5UwHcmtfDGz56XT28eW7F9IVSZfM1V3XlggrpfJ0hYFDcPkn80bskNxSmuRb9fRfEG5u2dRW8hFvkGVE8xDRQ3NhOWGlTsCCN+/DLQT7MrXayPXd/mYhn474oZYDi/os4m5JsWXZIKlrbK/dfi2d8IgOYFya517kudHTmerfeAtjkXmfMZjIyXo2f+OWJN9yqq0V6fsSZLPn6nOmsxQ=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
