kind: OnePasswordItem
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  itemPath: "vaults/k8s/items/grafana-admin-credentials"
