apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-audit-config
data:
  audit-logs.alloy: |-
    local.file_match "local_files" {
      path_targets = [{"__path__" = "/var/log/audit/**/*"}]
      sync_period = "5s"
    }

    loki.source.file "log_scrape" {
      targets    = local.file_match.local_files.targets
      forward_to = [loki.process.label_logs.receiver]
      tail_from_end = true
    }

    loki.write "grafana_loki" {
      endpoint {
        url = "http://loki.loki.svc:3100/loki/api/v1/push"
      }
    }

    loki.process "label_logs" {
      stage.labels {
        values = {
          job = "modsecurity",
        }
      }
      forward_to = [loki.write.grafana_loki.receiver]
    }
