apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-audit-config
data:
  audit-logs.alloy: |
    local.file_audit_logs "audit_logs" {
      path = "/var/log/audit/**/*"
      labels = {
        job = "audit-logs"
      }
      forward_to = [log_processor.receiver]
    }

    lokistack.write "default" {
      endpoint {
        url = "http://loki.loki.svc:3100/loki/api/v1/push"
      }
    }

    log_processor = loki.process "log_processor" {
      stage.json {}
      forward_to = [default.receiver]
    }
