apiVersion: v1
kind: ConfigMap
metadata:
  name: modsecurity-configs
data:
  base-config.conf: |
    # Enable scanning of the request body
    SecRequestBodyAccess On

    # Enable XML and JSON parsing
    SecRule REQUEST_HEADERS:Content-Type "(?:text|application(?:/soap\+|/)|application/xml)/" \
      "id:200000,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"

    SecRule REQUEST_HEADERS:Content-Type "application/json" \
      "id:200001,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=JSON"

    # Reject if larger (we could also let it pass with ProcessPartial)
    SecRequestBodyLimitAction Reject

    # Send ModSecurity audit logs to the stdout (only for rejected requests)
    SecAuditLog /dev/stdout

    # format the logs in JSON
    SecAuditLogFormat JSON

    # could be On/Off/RelevantOnly
    SecAuditEngine RelevantOnly
  base-config-prevent.conf: |
    Include /etc/nginx/modsecurity-configs/base-config.conf

    # Enable prevention mode. Options: DetectionOnly,On,Off
    SecRuleEngine On
  base-config-detect.conf: |
    Include /etc/nginx/modsecurity-configs/base-config.conf

    # Enable detection mode. Options: DetectionOnly,On,Off
    SecRuleEngine DetectionOnly
  geolookup.conf: |
    SecGeoLookupDb /etc/ingress-controller/geoip/GeoLite2-City.mmdb
    SecRule REMOTE_ADDR "@geoLookup" "phase:1,id:155,nolog,pass"
  custom-ip-blacklist.conf: |
    SecRule REMOTE_ADDR "@ipMatchFromFile /etc/custom-ip-blacklist/ip-blacklist.txt" \
      "id:1001,phase:1,deny,log,status:403,msg:\"Block Custom IP ranges (see ConfigMap custom-ip-blacklist)\""
  malicious-ip-300k-blacklist.conf: |
    # See https://github.com/romainmarcoux/malicious-ip
    SecRule REMOTE_ADDR "@ipMatchFromFile /etc/malicious-ip/full-300k-aa.txt" \
      "id:1002,phase:1,deny,log,status:403,msg:\"Block Malicious IPs\""
    SecRule REMOTE_ADDR "@ipMatchFromFile /etc/malicious-ip/full-300k-ab.txt" \
      "id:1003,phase:1,deny,log,status:403,msg:\"Block Malicious IPs\""
    SecRule REMOTE_ADDR "@ipMatchFromFile /etc/malicious-ip/full-300k-ac.txt" \
      "id:1004,phase:1,deny,log,status:403,msg:\"Block Malicious IPs\""
    SecRule REMOTE_ADDR "@ipMatchFromFile /etc/malicious-ip/full-300k-ad.txt" \
      "id:1005,phase:1,deny,log,status:403,msg:\"Block Malicious IPs\""
