apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: do-token
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  itemPath: "vaults/k8s/items/do-dns-token"
