apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
spec:
  project: infra
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://1password.github.io/connect-helm-charts'
      chart: connect
      targetRevision: 1.17.0
      helm:
        valueFiles:
          - '$values/values/1password-connect.yaml'
    - repoURL: 'https://github.com/siegy22/k8s-gitops.git'
      ref: values
