apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Infrastructure Apps
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Generic Applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: on-prem-infra
  namespace: argocd
spec:
  description: On-premise Infrastructure Apps
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: bootc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: on-prem-apps
  namespace: argocd
spec:
  description: On-premise cluster applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    name: bootc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
