# See https://medium.com/@qdrddr/argocd-app-with-helm-from-oci-repo-e52066647d99
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: bitnami-oci-repo
  namespace: argocd
stringData:
  enableOCI: 'true'
  name: bitnamicharts
  project: apps
  type: helm
  url: registry-1.docker.io/bitnamicharts
type: Opaque
---
