apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arnold-wordpress
spec:
  project: apps
  destination:
    namespace: arnold-wordpress
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'registry-1.docker.io/bitnamicharts'
      path: wordpress
      chart: wordpress
      targetRevision: 24.1.9
      helm:
        valueFiles:
          - '$values/values/arnold-wordpress.yaml'
    - repoURL: 'https://github.com/siegy22/k8s-gitops.git'
      targetRevision: main
      ref: values
      path: resources/arnold-wordpress
