apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: infra
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://kubernetes-sigs.github.io/external-dns'
      chart: external-dns
      targetRevision: 1.15.2
      helm:
        valueFiles:
          - '$values/values/external-dns.yaml'
    - repoURL: 'https://github.com/siegy22/k8s-gitops.git'
      targetRevision: main
      ref: values
      path: resources/external-dns
