apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
spec:
  project: apps
  destination:
    namespace: matrix
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://ananace.gitlab.io/charts'
      chart: matrix-synapse
      targetRevision: 3.11.1
      helm:
        valueFiles:
          - '$values/values/matrix.yaml'
    - repoURL: 'https://github.com/siegy22/k8s-gitops.git'
      path: charts/mautrix-whatsapp
      targetRevision: main
      helm:
        releaseName: mautrix-whatsapp
        valueFiles:
          - '$values/values/mautrix-whatsapp.yaml'
    - repoURL: 'https://github.com/siegy22/k8s-gitops.git'
      targetRevision: main
      ref: values
      path: resources/matrix
