apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  project: infra
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'ghcr.io/nginxinc/charts'
      path: nginx-ingress
      chart: nginx-ingress
      targetRevision: 1.4.0
      helm:
        valueFiles:
          - '$values/values/nginx-ingress.yaml'
    - repoURL: 'https://github.com/siegy22/k8s-gitops.git'
      targetRevision: main
      ref: values
