apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: infra
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://bitnami-labs.github.io/sealed-secrets/'
      chart: sealed-secrets
      targetRevision: 2.16.2
