apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-on-prem
spec:
  project: on-prem-infra
  destination:
    namespace: kube-system
    name: bootc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://helm.cilium.io/'
      chart: cilium
      targetRevision: 1.19.1
      helm:
        valueFiles:
          - $values/values/on-prem/cilium.yaml
    - repoURL: 'https://github.com/siegy22/k8s-gitops.git'
      targetRevision: main
      ref: values

