apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  project: on-prem-infra
  destination:
    namespace: metallb-system
    name: bootc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://metallb.github.io/metallb'
      chart: metallb
      targetRevision: 0.14.8
    - repoURL: 'https://github.com/siegy22/k8s-gitops.git'
      targetRevision: main
      path: resources/on-prem/metallb

