apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: about-me
  template:
    metadata:
      labels:
        app: about-me
    spec:
      serviceAccountName: about-me-sa
      containers:
      - name: web
        image: siegy22/web:1.1.0
        ports:
        - name: web-port
          containerPort: 8080
        resources:
          requests:
            cpu: "20m"
            memory: "10Mi"
          limits:
            cpu: "50m"
            memory: "20Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
        livenessProbe:
          httpGet:
            path: /
            port: web-port
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: web-port
          initialDelaySeconds: 2
          periodSeconds: 10
