apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: about-me-ingress
  annotations:
    # Disable external-dns picking this up, due to the same host name being on the matrix ingress
    # See https://github.com/kubernetes-sigs/external-dns/issues/819#issuecomment-1679122051
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: siegrist.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: about-me
            port:
              number: 8080
  tls:
  - hosts:
    - siegrist.io
    secretName: siegrist-io-tls
