apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: about-me-ingress
  annotations:
    # Disable external-dns picking this up, due to the same host name being on the matrix ingress
    # See https://github.com/kubernetes-sigs/external-dns/issues/819#issuecomment-1679122051
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      # this enables the default OWASP Core Rule Set
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf

      # Enable prevention mode. Options: DetectionOnly,On,Off (default is DetectionOnly)
      SecRuleEngine On

      # Enable scanning of the request body
      SecRequestBodyAccess On

      # Enable XML and JSON parsing
      SecRule REQUEST_HEADERS:Content-Type "(?:text|application(?:/soap\+|/)|application/xml)/" \
        "id:200000,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"

      SecRule REQUEST_HEADERS:Content-Type "application/json" \
        "id:200001,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=JSON"

      # Reject if larger (we could also let it pass with ProcessPartial)
      SecRequestBodyLimitAction Reject

      # Send ModSecurity audit logs to the stdout (only for rejected requests)
      SecAuditLog /dev/stdout

      # format the logs in JSON
      SecAuditLogFormat JSON

      # could be On/Off/RelevantOnly
      SecAuditEngine RelevantOnly

      SecRule GEO:COUNTRY_CODE "@pm CH CHE" \
        "id:10001,phase:1,deny,log,status:403,msg:\"Block Switzerland\""
spec:
  ingressClassName: nginx
  rules:
  - host: siegrist.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: about-me
            port:
              number: 8080
  tls:
  - hosts:
    - siegrist.io
    secretName: siegrist-io-tls
